In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
ar = arr

In [5]:
ar[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [6]:
ar[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
ar[10:0]

array([], dtype=int32)

In [9]:
ar_2d = np.arange(50).reshape(5,10)

In [14]:
ar_2d[1:3,3:]

array([[13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])

In [1]:
import numpy as np


In [2]:
ar = np.arange(0,11)

In [3]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
ar ** ar

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [5]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
ar / ar

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
ar % ar

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [8]:

np.sqrt(ar)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [10]:
ar + (ar - 3)

array([-3, -1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [11]:
ar + np.max(ar)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])